apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dummy-config
data:
  API_KEY: "sdbskdsnds2132mdsc"
  DB_URL: "mongodb://wede:efas@nkjdsdsaxs"
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-env-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo API_KEY=$API_KEY && echo DB_URL=$DB_URL && sleep 3600"]
    env:
    - name: API_KEY
      valueFrom:
        configMapKeyRef:
          name: my-dummy-config
          key: API_KEY
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: my-dummy-config
          key: DB_URL